# --- !Ups
create table "BLOGPOSTS" ("ID" INTEGER NOT NULL PRIMARY KEY, "TITLE" VARCHAR NOT NULL, "BODY" VARCHAR NOT NULL);

insert into BLOGPOSTS (5, "A blog post", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque volutpat placerat metus, eu lobortis mi feugiat vel. Nam ultricies id dui ac semper. Pellentesque in congue risus. Vestibulum lacinia scelerisque sapien quis accumsan. Sed eget molestie sapien. Fusce vehicula luctus nisi non venenatis. Curabitur laoreet, sapien quis placerat congue, lorem elit ornare nulla, quis accumsan erat est in dolor. Morbi mattis sapien id augue eleifend, sed egestas lorem mollis.")
insert into BLOGPOSTS (6, "A blog post", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque volutpat placerat metus, eu lobortis mi feugiat vel. Nam ultricies id dui ac semper. Pellentesque in congue risus. Vestibulum lacinia scelerisque sapien quis accumsan. Sed eget molestie sapien. Fusce vehicula luctus nisi non venenatis. Curabitur laoreet, sapien quis placerat congue, lorem elit ornare nulla, quis accumsan erat est in dolor. Morbi mattis sapien id augue eleifend, sed egestas lorem mollis.")
insert into BLOGPOSTS (7, "A blog post", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque volutpat placerat metus, eu lobortis mi feugiat vel. Nam ultricies id dui ac semper. Pellentesque in congue risus. Vestibulum lacinia scelerisque sapien quis accumsan. Sed eget molestie sapien. Fusce vehicula luctus nisi non venenatis. Curabitur laoreet, sapien quis placerat congue, lorem elit ornare nulla, quis accumsan erat est in dolor. Morbi mattis sapien id augue eleifend, sed egestas lorem mollis.")
insert into BLOGPOSTS (8, "A blog post", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque volutpat placerat metus, eu lobortis mi feugiat vel. Nam ultricies id dui ac semper. Pellentesque in congue risus. Vestibulum lacinia scelerisque sapien quis accumsan. Sed eget molestie sapien. Fusce vehicula luctus nisi non venenatis. Curabitur laoreet, sapien quis placerat congue, lorem elit ornare nulla, quis accumsan erat est in dolor. Morbi mattis sapien id augue eleifend, sed egestas lorem mollis.")
insert into BLOGPOSTS (9, "A blog post", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque volutpat placerat metus, eu lobortis mi feugiat vel. Nam ultricies id dui ac semper. Pellentesque in congue risus. Vestibulum lacinia scelerisque sapien quis accumsan. Sed eget molestie sapien. Fusce vehicula luctus nisi non venenatis. Curabitur laoreet, sapien quis placerat congue, lorem elit ornare nulla, quis accumsan erat est in dolor. Morbi mattis sapien id augue eleifend, sed egestas lorem mollis.")

# --- !Downs
drop table "BLOGPOSTS";

